# Generated by Django 5.1.2 on 2024-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Int', '0003_document_delete_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(auto_created=True, max_length=100),
        ),
    ]
