# Generated by Django 5.1.2 on 2024-10-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Int', '0004_alter_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
